### PR TITLE
Added DB

### PR DESCRIPTION
**Pull request by pratikshrma**
Code run's fine with -> npn run start
but there is a bug with -> npm run dev

### CODE REVIEW

**Review by cryogon — CHANGES_REQUESTED** [review]
Fix the array problem where it reinitialise everytime

**Comment by pratikshrma** [comment]
-> Array reinitialization Problem Fixed
->Delete Button Works now

-> Currently working on the restore button to restore the deleted tasks

**Comment by pratikshrma** [comment]
For the time being Mongo DB uri is exposed for convenience.

**Comment by cryogon** [comment]
> For the time being Mongo DB uri is exposed for convenience.

Just hide it on .env file later on

**Comment by cryogon** [comment]
Can you add `build:"node server.js"` in project.json script

**Comment by pratikshrma** [comment]
> Can you add `build:"node server.js"` in project.json script

Done.

**Review by cryogon — APPROVED** [review]

**Pull request merged**
